
-- Q1. what is the total revenue generated by male vs female customers?

SELECT 
    gender, SUM(purchase_amount) AS Total_revenue
FROM
    customer
GROUP BY gender;


-- Q2. which customers used a discount but still spent more than the average purchase amount?

SELECT 
    customer_id, purchase_amount
FROM
    customer
WHERE
    discount_applied = 'Yes'
        AND purchase_amount > (SELECT 
            AVG(purchase_amount)
        FROM
            customer);
            
            
-- Q3. which are the top 5 products with the highest average review rating?

SELECT 
    item_purchased,
    ROUND(AVG(review_rating), 2) AS average_rating
FROM
    customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;


-- Q4. compare the average purchase amounts between standard and express shipping?

SELECT 
    shipping_type, round(AVG(purchase_amount),2) as avg_revenue
FROM
    customer
WHERE
    shipping_type IN ('Express' , 'Standard')
GROUP BY shipping_type;


-- Q5. Do subscribed customers spend more? compare average spend and total revenue between subscribed and non-subscribed?

SELECT 
    subscription_status,
    COUNT(customer_id) AS total_customers,
    ROUND(AVG(purchase_amount), 2) AS avg_revenue,
    SUM(purchase_amount) AS total_revenue
FROM
    customer
GROUP BY subscription_status;


-- Q6. which 5 products have the higest percentage of purchases with discount applied?

SELECT 
    item_purchased,
    (COUNT(discount_applied) / (SELECT 
            COUNT(discount_applied)
        FROM
            customer
        WHERE
            discount_applied = 'Yes')) * 100 AS percentage
FROM
    customer
WHERE
    discount_applied = 'Yes'
GROUP BY item_purchased
ORDER BY percentage DESC
LIMIT 5;


-- Q7. segment customers into new, returning, and loyal based on their 
-- total number of previous purchases, and show the count of each segment.

SELECT 
    (CASE
        WHEN previous_purchases <= 10 THEN 'New'
        WHEN previous_purchases <= 35 THEN 'Returning'
        ELSE 'Loyal'
    END) AS customer_segment,
    COUNT(*) as number_of_customers
FROM
    customer
GROUP BY customer_segment;


-- Q8. what are the top 3 most purchased products within each category.

with item_counts as (
select category,item_purchased, 
count(*) total_orders,
row_number() over (partition by category order by count(*) desc) as item_rank
from customer
group by category,item_purchased)
select category,item_purchased,total_orders,item_rank
from item_counts
where item_rank<=3
;


-- Q9. are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe.

SELECT 
    subscription_status, COUNT(*) AS repeat_buyers
FROM
    customer
WHERE
    previous_purchases > 5
GROUP BY subscription_status;


-- Q10. what is the revenue contribution of each age group.

SELECT 
    age_group, SUM(purchase_amount) AS total_revenue
FROM
    customer
GROUP BY age_group
order by total_revenue desc;